services:
  angular:
    stdin_open: true
    container_name: angular
    build: ./angular
    volumes:
      - ./workDir/frontend:/var/www/frontend/:cached
    ports:
      - "4200:4200"
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - network_infrastructure
    command: ng serve frontend --host 0.0.0.0 --port 4200
  spring:
    build: spring
    container_name: spring
    tty: true
    command: mvn spring-boot:run
    networks:
      - network_infrastructure
    volumes:
      - ./workDir/backend:/home/spring/:cached
      - ./workDir/logs/:/var/log/nginx/:cached
    ports:
      - "8080:8080"
    depends_on:
      - MySQLDB
# MongoDB:
  #   image: mongo
  #   container_name: mongo_database
  #   ports:
  #     - "8081:8081"
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: p
  #     MONGO_INITDB_DATABASE: mongoDb
  #   volumes:
  #     - /var/lib/mongodb/
  #   networks:
  #     - network_infrastructure
  MySQLDB:
    image: mysql
    container_name: mysql_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: p
      MYSQL_DATABASE: mysqlDb
      MYSQL_USER: mysqlDbUser
      MYSQL_PASSWORD: p
    volumes:
      - /var/lib/mysql/
    networks:
      - network_infrastructure
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    links:
      - spring
      - angular
    volumes:
      - ./workDir/backend/:/home/spring:cached
      - ./workDir/frontend/:/var/www/frontend:cached
      - ./workDir/logs/:/var/log/nginx:cached
    networks:
      - network_infrastructure
networks:
  network_infrastructure:
    name: network_infrastructure
